language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=6fccaa5a7a240c1f4771cf3f4421c0a8e19ae9ffab7e8c4c80918eb5f9412669
matrix:
  include:
  - node_js: '12'
cache:
  directories: [node_modules]
install:
  npm
after_success: npm run test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESUL
