# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
  run_tests:
    docker:
      - image: cimg/node:18.16.1
        environment:
          CONNECTION_STRING: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        environment: 
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: node --version
      - run: whoami
      - node/install-packages
      - run:
          command: npm run test
          name: 'Execute test with mocha'
      - run:
          command: npm run coverage
          name: 'Upload Soverage'

# Invoke jobs via workflows.circle
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  run-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - run_tests
